-- Rename localized enum labels to English while preserving existing rows.
ALTER TYPE "ExhibitionType" RENAME VALUE 'PREVENDA' TO 'PRE_SALE';
ALTER TYPE "ExhibitionType" RENAME VALUE 'EXIBICAO_NORMAL' TO 'REGULAR_SCREENING';
ALTER TYPE "ExhibitionType" RENAME VALUE 'REEXIBICAO' TO 'RERUN';
ALTER TYPE "ExhibitionType" RENAME VALUE 'ESPECIAL' TO 'SPECIAL';

ALTER TYPE "SessionType" RENAME VALUE 'PREVENDA' TO 'PRE_SALE';

ALTER TYPE "SessionState" RENAME VALUE 'DISPONIVEL' TO 'AVAILABLE';
ALTER TYPE "SessionState" RENAME VALUE 'LOTADO' TO 'SOLD_OUT';
ALTER TYPE "SessionState" RENAME VALUE 'CANCELADO' TO 'CANCELED';
